%YAML:1.0
## input files
tagModelFile: "./config/Topotag_3x3_circle_model.dat"      # [STRING]

## tag setup
tagBitSize: 3
tagLength: 0.45   # [DOUBLE] tag length of the white area, unit: m
binFactor: 0.95   # [DOUBLE] image binary factor

## camera calibration params
cameraMatrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [573.200, 0, 601.796, 0, 572.459, 409.043, 0, 0, 1]
distortionCoefficients: !!opencv-matrix
   rows: 8
   cols: 1
   dt: d
   data: [0.74745, -0.0234192, 0.000148958, -0.000149384, -0.00925629, 1.07979, 0.129308, -0.0305814] 
